const actWeather = {
    GET_DATA_WEATHER: "GET_DATA_WEATHER",
    SET_DATA_WEATHER: "SET_DATA_WEATHER",

    GET_DATA_DETAIL: "GET_DATA_DETAIL",
    SET_DATA_DETAIL: "SET_DATA_DETAIL",

    GET_DAYS: "GET_DAYS",
    SET_DAYS: "SET_DAYS",
}
export default actWeather;